export const SET_CITIES = "SET_CITIES";
export const SET_CITY = "SET_CITY";
export const SET_FILTERED_CITIES = "SET_FILTERED_CITIES";

export const SET_APP_MESSAGE = "SET_APP_MESSAGE";
export const SET_IS_XHR_RUNNING = "SET_IS_XHR_RUNNING";
